---
- name: "mkdir ~/bin"
  ansible.builtin.file:
    path: ~/bin
    state: directory
    mode: 0700
  tags:
    - github

- name: Check if ~/bin/gh exists
  ansible.builtin.stat:
    path: ~/bin/gh
  register: bin_gh
  tags:
    - github

- name: print gh stat
  ansible.builtin.debug:
    var: bin_gh
  tags:
    - github

- name: Copy down the github cli binary
  ansible.builtin.unarchive:
    src: https://github.com/cli/cli/releases/download/v2.5.2/gh_2.5.2_linux_amd64.tar.gz
    dest: ~/
    remote_src: yes
    extra_opts:
      - --strip-components=1
      - gh_2.5.2_linux_amd64/bin/gh
  tags:
    - github
