# Based on https://www.redhat.com/sysadmin/ansible-configure-vim
- name: Config Vim with plugins
  hosts: localhost
  gather_facts: yes
  become: no
  vars:
    vim_dir: "{{ ansible_env.HOME }}/.vim"
    fzf_dir: "{{ ansible_env.HOME }}/.fzf"

  tasks:
    - name: clone fzf git repo
      git:
        dest: "{{ fzf_dir }}"
        repo: https://github.com/junegunn/fzf.git
        clone: yes
        depth: 1
        update: yes

    - name: Install fzf binary
      command: "{{ fzf_dir }}/install --bin"
      args:
        creates: "{{ fzf_dir }}/bin/fzf"

    - name: Ensure .vim/{autoload,bundle} directory exists
      file:
        path: "{{ item }}"
        state: directory
        recurse: no
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"

    - name: Install vim-plug
      get_url:
        dest: "{{ vim_dir }}/autoload/plug.vim"
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
