#!/bin/bash

# Run the pip-installed system ansible. This fixed the missing python-apt
# problem
export PATH="/usr/local/bin:${PATH}"

# Ask or become password if not specified in environment
if [ -z "${ANSIBLE_BECOME_PASS}" ]; then
  OPTIONS="--ask-become-pass"
fi
ansible-playbook site.yml  ${OPTIONS} "$@"
