---
name: Lint
on: [push, pull_request]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.0

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v4.1.0.post0
        with:
          targets: "./"
          args: ""
